### PR TITLE
Issue/135 select component

### PR DESCRIPTION
**Pull request by aegis301**

### CODE REVIEW

**Comment by aegis301** [comment]
by request from @use-to my draft PR. Stylings are not perfectly matching what the description displayed, WIP.

**Comment by aegis301** [comment]
One question I asked myself is how we want to handle Items in the dropdown menu of different lengths. Adjusting the initial select button to the max length of the items in the list? Overflowing with a `Itemwithsuperhighlen...`?

**Comment by DasProffi** [comment]
> One question I asked myself is how we want to handle Items in the dropdown menu of different lengths. Adjusting the initial select button to the max length of the items in the list? Overflowing with a `Itemwithsuperhighlen...`?

We could also just wrap the text to a second line, unless the menu items don't allow that

**Comment by use-to** [comment]
Yeah, or just use `text-overflow: ellipsis` for single line options.

**Comment by use-to** [comment]
@aegis301 remember to
- [ ] fix the ci (there are some linting issues)
- [ ] remove your changes made in `pages/index.tsx`
before marking this pr as `Ready For Review`

**Review by use-to — APPROVED** [review]

**Comment by florian-sabonchi** [comment]
I think it would be useful to set our primary color at the focus

**Pull request merged**
