### PR TITLE
Contact page

### LINKED ISSUE #33: Contact page
The contact form on that page should track name, email and a message.

### PR DESCRIPTION
**Pull request by MaxSchaefer**
Closes #33 

Bildschirmfoto 2022-12-14 um 10 01 25 PM

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
@JannikWibker thanks for that nice GridBox, let's build on top of this!

**Comment by JannikWibker** [comment]
I'm not sure if using `<GridBox />` all over the place is such a good idea. Don't get me wrong, the contact page design looks nice but I don't want to over-use the "grid" effect

I'll try to come up with another design idea shortly, in the meantime we can merge this if it that is desired for the time being

**Comment by use-to** [comment]
> I'm not sure if using `<GridBox />` all over the place is such a good idea. Don't get me wrong, the contact page design looks nice but I don't want to over-use the "grid" effect
> 
> I'll try to come up with another design idea shortly, in the meantime we can merge this if that is desired for the time being

I like the the  "grid" effect but maybe we should consider changing the team page to cover more details. What about changing the team page a bit and remain this site as it is?

**Review by use-to — APPROVED** [review]

**Comment by use-to** [comment]
@MaxSchaefer: As @JannikWibker said you could merge this and we will talk about it later on...

**Pull request merged**
