### PR TITLE
pin versions

### LINKED ISSUE #484: Pin versions
### Describe the chore

Currently, we are facing issues when running `pnpm install` throwing error, because packages are updated. Until the time, we are upgrading our package versions, we should pin them to a working one.

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #484

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
Please use https://docs.renovatebot.com/configuration-options/#rangestrategy instead of manually pinning the dependencies.

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
Please use https://docs.renovatebot.com/configuration-options/#rangestrategy instead of manually pinning the dependencies.

**Comment by use-to** [comment]
Yeah, this is pain, but shouldn't we just fix the issues after installing new packages instead?

**Comment by DasProffi** [comment]
> Yeah, this is pain, but shouldn't we just fix the issues after installing new packages instead?

That's the plan, but with the current changes to information passing with contexts and the backend integration, changing the code after a major update of the packages would be too much workload to make effective progress.

Therefore, we want to delay this for now by version pinning

**Comment by use-to** [comment]
This pr has currently no progress. Is help wanted @DasProffi ?

**Comment by DasProffi** [comment]
> This pr currently has no progress. Is help wanted @DasProffi ?

I discussed it with @MaxSchaefer he wanted to check my proposed versioning and then change the renovate config

**Review by MaxSchaefer — APPROVED** [review]

**Pull request merged**
