### PR TITLE
Create basic dashboard navigation primitives

### LINKED ISSUE #5: Create basic dashboard navigation primitives
- Different routes / views for our erd entities
- Mock for user settings / user-icon in navbar
- Settings page
- Button component (maybe some others as well)

### PR DESCRIPTION
**Pull request by JannikWibker**
closes #5

### CODE REVIEW

**Comment by JannikWibker** [comment]
Header:
image

**Comment by use-to** [comment]
Cloudflare Pages blocked this pr!
The "old" problem was caused by an outdated node version.
> new node version is `16.14.1 (LTS)`
At the moment cf-pages only takes care of the landing page. This will change in the future!

**Comment by use-to** [comment]
@JannikWibker could you check the status of this pr?

**Comment by JannikWibker** [comment]
image

This new profile page is mostly in line with the new design in figma, however some things are unfinished and not completely implemented.
This is the same for the actual design in figma as well so this isn't really that much of a problem.
Everythings still heavily in the *prototype-and-fuck-around*-phase

**Review by MaxSchaefer — APPROVED** [review]

**Pull request merged**
