### PR TITLE
outline overdue tasks

### LINKED ISSUE #383: Red outline for overdue tasks
To indicate overdue tasks, the first approach in our UI, should be to strongly outline these tasks with a red border.

### PR DESCRIPTION
**Pull request by DasProffi**
closes #383

### CODE REVIEW

**Comment by Paul-B98** [comment]
hey, maybe we should sync our pull request? in #387 are some change that introduce a date picker

**Comment by DasProffi** [comment]
> hey, maybe we should sync our pull request? in #387 are some change that introduce a date picker

Makes sense, I will merge your PR into this one, so you can close yours

**Review by use-to — CHANGES_REQUESTED** [review]
We definitely need time as well. So can we pick a datetime instead of date?

**Comment by DasProffi** [comment]
In the long run, we should probably consider another component just for date/datetime input or search packages that do so

**Review by use-to — APPROVED** [review]

**Pull request merged**
