### PR TITLE
add organizations backend connection and invites

### LINKED ISSUE #434: Overview of users invitations
We need to have an overview to manage invitations for the current user. In this overview, the user should be able to accept and decline invitations. The overview should be s simple list of the invitations and lives inside the user menu.

### LINKED ISSUE #475: Invite user into organization by email
The button "Add member" on the organization details view, should open a simple modal where the user can enter an email address for the invitation.

The action buttons inside the modal should be "Invite", "Invite and next" and "Cancel".

- "Invite" should send the invite and closes the modal afterward
- "Invite and next" should send the invite and resets the modal afterward
- "Cancel" should close the modal

### LINKED ISSUE #498: Adopt `lib/Tables` on members table on organization details view
### Describe the feature

Adopt `lib/Tables` on members table on organization details view

### Why is this feature needed?

because we have a new component for tables, which creates less overhead

### Additional context

_No response_

### LINKED ISSUE #510: Create, read, update and delete organizations on over- and detailview

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #434
closes #510
closes #475
closes #498

## [OPTIONAL] Give testing instructions to reviewers
Look at `organizations/<uuid>`

### CODE REVIEW

**Comment by DasProffi** [comment]
blocked by https://github.com/helpwave/services/issues/299

**Comment by DasProffi** [comment]
There are still problems with backend endpoints see #305 and #306, and additionally we have option for removing a send request from the sender side as decline only allows the user to decline their invites

**Comment by DasProffi** [comment]
> Looks like there is a problem with editing an organisation in this pull request.

What are you refering to? The ids as name and email are a backend issue

**Review by use-to — APPROVED** [review]
All views and concepts included. Please track the open issues with the orga management (like the uuids as names, no profile pictures, and so on...)  @DasProffi 
We should think about an invitation banner on the overview page, too.

Also please set all the profile pictures to these boring avatars we're using all the time. The mvp will not yet be able to upload images.

All this is optional, so here you go 👍🏻 🚀

**Comment by DasProffi** [comment]
Optional Features issues:
#533
#534

**Pull request merged**
