### PR TITLE
fix: handle text-overflow in organization card component

### LINKED ISSUE #208: Overlapping Issue on to many Members on one ward
image

### PR DESCRIPTION
**Pull request by florian-sabonchi**
Closes #208

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
@florian-sabonchi does this pull request closes #208? Please don't forget to use the `Close` keyword in the future.

**Comment by MaxSchaefer** [comment]
When does this issue occurs? The screenshot is from the current main.

Bildschirm­foto 2023-04-18 um 10 17 49 PM

**Review by use-to — CHANGES_REQUESTED** [review]
I would also argue that this change (if it makes sense/is necessary then) should be made inside the `AvatarGroup` component.

**Comment by florian-sabonchi** [comment]
> When does this issue occurs? The screenshot is from the current main.
> 
> Bildschirm­foto 2023-04-18 um 10 17 49 PM

seems to be fixed

**Comment by florian-sabonchi** [comment]
https://user-images.githubuserconten@MaxSchaefer m/54689374/233166073-b0cbc891-008a-4464-9709-ae1983dc11b7.mp4

@max

**Comment by florian-sabonchi** [comment]
But it seems i made a mistake, i will fix that soon

**Comment by florian-sabonchi** [comment]
image

**Comment by florian-sabonchi** [comment]
image

**Review by use-to — APPROVED** [review]

**Pull request merged**
