### PR TITLE
add SearchableSelect to task AssigneeSelect

### LINKED ISSUE #741: Searchable select for task assignee
### Describe the feature

When the user opens the dropdown, the user should be able to search through the list by start typing. Please develop this component generic.

### Why is this feature needed?

The user should be able to search through the list of possible assignees for faster assignment. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #741

### CODE REVIEW

**Review by use-to — CHANGES_REQUESTED** [review]
Looks good to me, but two more ideas:
1. could we autofocus the input field on select click?
2. we should limit the displayed organization members to at maximum 3 or 5

**Comment by DasProffi** [comment]
> 1. could we autofocus the input field on select click?

Will be done
> 2. we should limit the displayed organization members to at maximum 3 or 5

Only display 5 in a scrollable or actually only show 5?

**Comment by use-to** [comment]
> > 1. could we autofocus the input field on select click?
> 
> Will be done
> 
> > 2. we should limit the displayed organization members to at maximum 3 or 5
> 
> Only display 5 in a scrollable or actually only show 5?

Scrollable would be nice, too. If we want to implement lazy loading later on we could do that.
Feel free!

**Comment by DasProffi** [comment]
> Scrollable would be nice, too. If we want to implement lazy loading later on we could do that. Feel free!

The default `Select`, already scrolls, if the content exceeds more than 30% of the screen height, thus this is already implemented

**Review by use-to — APPROVED** [review]
Very nice! You're right, the selection is scrollable. But let's keep this in mind for lazy loading later on...

@MaxSchaefer The tasks preview on fly.io is not updating... Maybe this is due to the cancellation before.

**Pull request merged**
