### PR TITLE
fix: replaced  <Trash/> with translation.remove

### LINKED ISSUE #280: Design should be uniform
Instead of the trashicon, we should write out "remove" just as in the other pages.

Bildschirmfoto vom 2023-04-23 15-27-50

### PR DESCRIPTION
**Pull request by florian-sabonchi**
closes #280

### CODE REVIEW

**Comment by shivadharmi** [comment]
@florian-sabonchi looking good. But, the build got failed. Reason?

**Review by shivadharmi — APPROVED** [review]
@florian-sabonchi looking good. But, the build got failed. Do you know the reason?

**Comment by MaxSchaefer** [comment]
Got it. CI is green.

@shivadharmi our CI step on Cloudflare is sometimes flaky and fails for no reason. I've triggered an rerun.

**Review by MaxSchaefer — APPROVED** [review]

**Comment by shivadharmi** [comment]
> Got it. CI is green.
> 
> @shivadharmi our CI step on Cloudflare is sometimes flaky and fails for no reason. I've triggered an rerun.

Okay @MaxSchaefer got it.

**Pull request merged**
