### PR TITLE
feat: mediquu page

### LINKED ISSUE #980: `/placeholderbrand` becomes `/mediquu`
### Describe the feature

Please replace logos and brand-names. More content will follow, some texts are ready on Figma, for example the brand-texts.

### Why is this feature needed?

Based on #974, we are ready to disclose informations about mediQuu. This issue tracks the initial swap of placeholder content like logos and company names.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #980

## [OPTIONAL] Give testing instructions to reviewers
Look at `/mediuuu`

### CODE REVIEW

**Comment by DasProffi** [comment]
- [ ] Texts for FAQ Section

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
About mediQuu:
```
DE:
Seit 2015 sorgen wir für eine komfortable und übergreifende Vernetzung von Versorg​ern und Leistungserbringern im Gesundheitswesen. Unser Ziel ist stets eine bedarfsgerechte Entwicklung von digitalen Diensten, um die Vernetzung aller Aktuere zu vereinfachen und neue Möglichkeiten zu schaffen. Zukünftig werden wir diesen Weg mit dem starken Team der helpwave GmbH beschreiten.

EN:
Since 2015, we have been ensuring a comfortable and comprehensive networking of providers in the healthcare sector. Our goal is always a demand-oriented development of digital services to simplify the networking of all actors and create new possibilities. In the future, we will pursue this path with the strong team of helpwave GmbH.
```

Christian Remfert info text:
```
DE:
Zuständig für die konzeptionelle und technische Umsetzung der mediQuu-Plattform, zukünftig beratend tätig.

EN:
Responsible for the conceptual and technical implementation of the mediQuu platform, providing advisory services in the future.
```

Peter Körner info text:
```
DE:
Zuständig für die konzeptionelle und visuelle Umsetzung der mediQuu-Plattform, zukünftig beratend tätig.

EN:
Responsible for the conceptual and visual implementation of the mediQuu platform, providing advisory services in the future.
```

**Comment by MaxSchaefer** [comment]
I am on the FAQ right now

**Comment by MaxSchaefer** [comment]
First time landing-page visitors that are entering our site via `helpwave.de/mediquu` are falling back to `de` as the default language.

**Review by use-to — APPROVED** [review]
First stage approval. We might need to update some stuff later on in cooperation with mediQuu as we can't request their review here on GitHub.
I'll take responsibility now for further content-wise updates while checking with mediQuu.

Thank you @DasProffi and @MaxSchaefer

**Comment by MaxSchaefer** [comment]
> At the time you read this I'll probably be airborne.

😅 ... 👀 Flightradar

**Review by MaxSchaefer — APPROVED** [review]

**Comment by DasProffi** [comment]
> First stage approval. We might need to update some stuff later

We still need to update the social links for the fromer mediquu team @use-to @MaxSchaefer

**Pull request merged**
