### PR TITLE
add task mutations

### LINKED ISSUE #499: Create, update and delete tasks on kanban

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #499

### CODE REVIEW

**Review by use-to — CHANGES_REQUESTED** [review]
Just found some problems regarding the subtask creation and creation of a task without notes.

**Comment by DasProffi** [comment]
> Just found some problems regarding the subtask creation and creation of a task without notes.

Could you describe them? And notes are required by the backend currently, therefore that will be fixed there.

**Comment by MaxSchaefer** [comment]
> > Just found some problems regarding the subtask creation and creation of a task without notes.
> 
> Could you describe them? And notes are required by the backend currently, therefore that will be fixed there.

https://github.com/helpwave/services/issues/280

**Comment by DasProffi** [comment]
@use-to are the issues fixed now or do you still have them?

**Comment by use-to** [comment]
> @use-to are the issues fixed now or do you still have them when creating tasks?

Cant test it atm. I will approve because you implement that in services.

**Review by use-to — APPROVED** [review]

**Pull request merged**
