### PR TITLE
add generic table

### LINKED ISSUE #442: Table component
We have similar components in `RoomList` and `OrganizationMemberList`. We should consider combining these two table into one generic component.

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #442

## Testing
look at `/examples/table`

### CODE REVIEW

**Review by use-to — CHANGES_REQUESTED** [review]
Looks very promising, BUT we got an unwanted behavior:
1. Click the upper left button (checkbox - select all) 
2. Create a new data item
3. The item should be selected or at least the checkbox should change to a "minus"-sign

**Comment by use-to** [comment]
I would like to know the opinion of @JannikWibker to this table component, as he already mentioned some barriers and potential difficulties before. Do you mind?

**Comment by use-to** [comment]
Also, are we using storybook for now? Maybe we should start moving our examples there...

**Comment by DasProffi** [comment]
> Looks very promising, BUT we got an unwanted behavior:
> 
> 1. Click the upper left button (checkbox - select all)
> 2. Create a new data item
> 3. The item should be selected or at least the checkbox should change to a "minus"-sign

I would call this intentional as an added item it should not be selected, but maybe deselecting all on add would be a more user friendly (or at least understandable) alternative

**Comment by JannikWibker** [comment]
Use https://tanstack.com/table/v8 if possible
Tables are notoriously hard to do yourself and you'll start having new features creep up in no time which you need.
Hastily adding them to something existing without having considered them outright can turn out nasty if you have to do it quite a lot of times.

Tanstack table has a lot of features you don't need (for now; maybe ever) but there's quite a lot of useful stuff which you can save development time on (column groups, sorting, filtering, pagination, custom data accessors, column widths, virtualized table rows, selecting rows, toggling column visibility, expanding rows into multiple rows, ...)

Sadly their documentation is basically non-existent so get used to searching in the source code (pressing `.` on the repo page is a godsend) and browsing their examples

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
- Using a tri state to indicate the sorting ([icon](https://lucide.dev/icons/chevrons-up-down))
- Jump to the inserted item

**Comment by MaxSchaefer** [comment]
> Use [tanstack.com/table/v8](https://tanstack.com/table/v8) if possible Tables are notoriously hard to do yourself and you'll start having new features creep up in no time which you need. Hastily adding them to something existing without having considered them outright can turn out nasty if you have to do it quite a lot of times.
> 
> Tanstack table has a lot of features you don't need (for now; maybe ever) but there's quite a lot of useful stuff which you can save development time on (column groups, sorting, filtering, pagination, custom data accessors, column widths, virtualized table rows, selecting rows, toggling column visibility, expanding rows into multiple rows, ...)
> 
> Sadly their documentation is basically non-existent so get used to searching in the source code (pressing `.` on the repo page is a godsend) and browsing their examples.
> 
> You'll likely want controlled table state at some point as well (external search field, persisting filters/.. to localStorage), one idea which makes this quite easy is turning your whole table logic into a hook and then breaking your table component down into a few large components (header item, pagination, row, row item, ..). This way you can offer both a controlled and an uncontrolled variant without having (a lot of) duplicate code or inconvenience.
> 
> CC: @DasProffi @use-to

Thanks for the write-up. I agree with you 100% about the potential scope creep of a custom table component. But I think that TanStack Table, due to the lack of their documentation, is not a good fit. Until we evaluate other table components, we should adopt the new one from @DasProffi. Our table component as a thin API, we will adopt a potential table library with ease. How is the state handled in TanStack Table and do you have other recommendations of table components @JannikWibker?

**Comment by use-to** [comment]
> > Looks very promising, BUT we got an unwanted behavior:
> > 
> > 1. Click the upper left button (checkbox - select all)
> > 2. Create a new data item
> > 3. The item should be selected or at least the checkbox should change to a "minus"-sign
> 
> I would call this intentional as an added item it should not be selected, but maybe deselecting all on add would be a more user friendly (or at least understandable) alternative

Yeah, I will leave that up to you. But please ensure that at least the checkbox in the Header bar is showing a minus then as there is the new item displayed.

**Comment by JannikWibker** [comment]
Only ever used react-table and tanstack table (same library, rebranded with the v7 to v8 update which changed pretty much everything)

I think the lack of documentation is something you can get past with enough time/commitment, it'll be annoying though (I had to do it twice, once for v7, once for v8)

I don't know of any other headless table libraries but the tips about splitting your table into a few components and creating an all encompassing hook still stands unrelated to whether you use tanstack table or not

**Review by MaxSchaefer — APPROVED** [review]

**Comment by MaxSchaefer** [comment]
@use-to our requested changes are implemented. 🎉

**Review by use-to — APPROVED** [review]

**Pull request merged**
